// priority: 900
RegistryOrganTooltip(new MultiStateTooltip('better_expansion:rusty_mechanical_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.furnace_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.furnace_core.alt.1', Text.gold('100')))
    .addAlt(Text.translatable('tooltips.kubejs.furnace_core.alt.2', Text.gold('2'), Text.gold('5')))
    .addAlt(Text.translatable('tooltips.kubejs.furnace_core.alt.3'))
    .addCtrl(RevolutionFlameType)
    .addCtrl(Text.translatable('tooltips.kubejs.furnace_core.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.furnace_core.ctrl.2'))
)

RegistryOrganTooltip(new MultiStateTooltip('better_expansion:mechanical_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.burning_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.burning_heart.alt.1', Text.gold('5')))
    .addAlt(Text.translatable('tooltips.kubejs.burning_heart.alt.2', Text.gold('100%')))
    .addAlt(Text.translatable('tooltips.kubejs.burning_heart.alt.3'))
    .addCtrl(RevolutionFlameType)
    .addCtrl(Text.translatable('tooltips.kubejs.burning_heart.ctrl.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('better_expansion:rusty_mechanical_rib_left')
    .addDefault(Text.translatable('tooltips.kubejs.energy_bottle_red.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.energy_bottle_red.alt.1', Text.gold('100')))
    .addAlt(Text.translatable('tooltips.kubejs.energy_bottle_red.alt.2', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.energy_bottle_red.ctrl.1', Text.gold('300%')))
    .addCtrl(RevolutionFlameType)
    .addCtrl(Text.translatable('tooltips.kubejs.energy_bottle_red.ctrl.2', Text.gold('200%')))
)

RegistryOrganTooltip(new MultiStateTooltip('better_expansion:mechanical_rib_left')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_cable.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_cable.alt.1', Text.gold('1')))
    .addAlt(Text.translatable('tooltips.kubejs.revolution_cable.alt.2', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.revolution_cable.ctrl.1', Text.gold('300%')))
)